server:
  port: 8882
  servlet:
    session:
      timeout: 1440m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/neu-competition?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: chikuanpeng2002
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
    count: countSql
neumall:
  # 工作路径，包含上传的所有资源的存储目录，必须以/结尾
  workspace: C:/contest/
  #  workspace: D:/runtime/neumall/
  resource-prefix: /res/

file:
  upload-dir: /static/image/